#!/usr/bin/env php
<?php

use Smatyas\GCloudManager\Command\Compute\InstancesListCommand;
use Smatyas\GCloudManager\Command\Compute\InstancesStartCommand;
use Smatyas\GCloudManager\Command\Compute\InstancesStopCommand;

set_time_limit(0);

$app = require_once __DIR__.'/bootstrap.php';

$application = $app['console'];
$application->add(new InstancesListCommand());
$application->add(new InstancesStartCommand());
$application->add(new InstancesStopCommand());
$application->run();
