#!/usr/bin/env php
<?php

use Smatyas\GCloudManager\Command\Compute\InstancesListCommand;

set_time_limit(0);

$app = require_once __DIR__.'/bootstrap.php';

$application = $app['console'];
$application->add(new InstancesListCommand());
$application->run();
